### ISSUE TITLE
Make a tutorial and demonstration video to be included in the readme / documentation.

### ISSUE THREAD

**Issue by boltex** [boltex/leointeg#114]
Edit :  Needs #43 and #30

First version done at https://www.youtube.com/watch?v=SYwlfdEukD4

**Comment by celtic-coder** [comment]
Hi Felix (@boltex),

The YouTube video is instructive. Perhaps an introduction at the beginning, (like the summary at the end), would be helpful? Since clones are such a significant  feature, maybe a further sentence or two on their advantages and uses?

The screenshots at the end, along with the keyboard shortcuts, are helpful and a pointer towards things to come!

Kind Regards,
Liam

**Comment by boltex** [comment]
@celtic-coder 

Thank you Liam!

This is exactly the kind of suggestions that I hoped to gather and accumulate before I make the next iteration of this video. 

It's greatly appreciated to receive tips from someone like you who has experience in marketing, as it is an aspect that I try to cover too with the leoInteg project. (Promo videos, dedicated website, polished and professional look and feel, etc...)

Thanks again!
Félix
