### ISSUE TITLE
Unable to install extension 'boltex.leointeg' as it is not compatible with VS Code '1.57.1'.

### ISSUE THREAD

**Issue by tbpassin** [boltex/leointeg#166]
Best say what version of VSC is needed ...

**Comment by boltex** [comment]
Thank you for trying out leointeg!! :)

I'll add mentions in the readme, and in further releases announcements that leointeg needs the somewhat latest release of vscode to work. (or close to it)

On the other hand, vscode tries to auto-update itself after using it for a couple of minutes if it has access to the internet. (Or at least the 'gear' icon at the bottom left of the screen will have a '1' overlaid on it, specifying that it will apply updates if closed-and-restarted.

You can also force a check / update by going to the far right on the top menu to 'help' -> 'check for updates'

(I'll close this issue when I add a mention about that in the next leointeg beta release/fix.)

Thanks again!

**Comment by tbpassin** [comment]
Yes. I saw that VSC was ready to update, and after that the extension installed.  It's now at 1.58.2.

**Comment by boltex** [comment]
Since vscode automatically tries to auto-update. and the fact that I wont increment the required version in the future (i dont see any new leointeg features requiring features from vscode that would appear in later versions of vscode) this situation is not likely to reapear, and the message about the compatibility is clear enough in my understanding that vscode just needs to be updated to a later version is it ever arises.

So I'll close this issue for now.
