### ISSUE TITLE
How To Bind Leo Command to Hot Key

### ISSUE THREAD

**Issue by tbpassin** [boltex/leointeg#167]
Not exactly an "issue", but how do I bind a Leo command I've written to a hot key in VSC?  I think you covered this in some thread on Google Groups Leo, but It's hard to find.

Going along with this, how can I find the VSC hot keys already in use?

**Comment by boltex** [comment]
Hmmm, best i can do for now is provide the @buttons to let you bind code you've written in Leo... 

but! ...you just gave me an interesting idea: I'll reserve/pre-make a limited number of 'user commands' which will be assignable to a command or 'chunk of code' in Leo, akin to it's @button system, and let the user define them, and assign a keybind to it as they will be mapped to a couple of 'premade-generic' commands. (probably going to be named 'leo custom 1' ... through 10 or something like that!

So thanks for your input. I'll keep this issue open to accumulate notes and comments about this nice feature idea!

**Comment by boltex** [comment]
@tbpassin  You can also use the minibuffer, if you meant to access a command that you wrote, which is in the Leo codebase itself already!

(unless you meant how to actually add a command to leointeg itself, at the extension level?) 

Thing is, I,m not sure what you meant originally with "Leo command I've written" so I've provided a couple of answers that cover some possible interpretations of your question.

**Comment by tbpassin** [comment]
Sounds good.  Would that be on a per-outline basis (preferred)?

Don't forget that sometimes we want to remove a button!

**Comment by boltex** [comment]
Good point. when I make pre-made custom buttons, I'll make the mapping of assignments 'workspace based'. Instead of one general set of keybinding-per-custom-command...

 (workspace in VSCode parlance is the project 'folder' it's got open in one of it's window instance.)

Thanks again for your input!

**Comment by tbpassin** [comment]
I'm having trouble when an outline is changed.  Restarting VSC didn't seem to make a difference.

1. Have outline open in both Leo and vsc. change body text in vsc.  Leo opens a dialog that says the outline has been changed outside of Leo, do I want to restart Leo?  If Yes, Leo closes and reopens with the changes.  If No, Leo continues without any changes to the outline, and now Leo and vsc are out of sync.

It should not be necessary to restart leo to make a change to the body.  I suppose this may be a bridge problem rather than a leointeg one.

2. In the reverse direction, when I make a change to an outline in Leo, vsc notices and asks if I want to update the outline in vsc.  If Yes, the outline in vsc gets updated. This seems like correct behavior to me.

These observations make me concerned as to what to do if the two outlines get out of sync.  As a workaround, you can always make another harmless change in one and get them re-synced that way, but I think we would need a better solution.

**Comment by tbpassin** [comment]
I've been seeing some error messages that say

`NotImplementedError: Unknown node type: option_list at C:\Tom\git\leointeg\node_modules\mkdirp\bin\usage.txt:9`

I don't think they are causing trouble, but better not to have them, maybe?

**Comment by tbpassin** [comment]
I just checked if leointeg works if started with no leo window open (as it should).  Yes, it does.

**Comment by tbpassin** [comment]
One thing that should be explained somewhere, I'm not sure where.  If you run a script that uses print(), you will see that output in the vsc console window for "LeoBridge Server"  That's logical, but I was going nuts trying to see where the output was before I discovered it.

**Comment by boltex** [comment]
Thanks your your question ! Much appreciated! 

But, I'm not sure I understand your points about 'having trouble when an outline is changed. Restarting VSC didn't seem to make a difference'...

I've read your post 3 times... maybe there's something I'm missing... Can you give the 'expected' behavior at each point? (also notice that when trying to open a Leo file with multiple instances of 'regular' Leo, a message appears to make sure you want this, because it's really error prone!) 

(BTW, this is another reason as to why the 'automatically opened recent files' list should be saved by workspace and not all globally for the user/machine because otherwise opening 2 instances of vscode on 2 different projects/folders will open the same set of Leo file(s) ! )

Restarting the Leo file itself (not refreshing @files nodes etc, but the .Leo file itself, if changes are detected with the .Leo file) is one of the last features I did, and really may need more testing/debugging - So, many thanks for the reports you're providing!! :)

Also, please precise if those 'saving' also change an @file, @clean, etc. as those will trigger a change detection and either refresh it - or prompt you about it also.

**Comment by boltex** [comment]
About your other point, yeah, you're right,... I only recently discovered that some people use the 'print' statement in Leo as I only did use the g.es() personally since 2002 heheh! ... (as I not mainly a python coder it's what made sense to me. But I'll leave it like that for now unless you have a suggestion to make about this particular point) 

great point nonetheless, so thanks again for that!

**Comment by boltex** [comment]
@tbpassin sidenote: please create other issues for different topics :) thanks! (I'll note & condense those great conversations and subjects split in different issues some time later )

**Comment by edreamleo** [comment]
On Mon, Jul 19, 2021 at 10:11 PM Felix ***@***.***> wrote:

> I'll reserve/pre-make a limited number of 'user commands' which will be
> assignable to a command or 'chunk of code' in Leo, akin to it's @button
> <https://github.com/button> system, and let the user define them, and
> assign a keybind to it...


Sounds like a good plan to me.

Edward

**Comment by edreamleo** [comment]
On Mon, Jul 19, 2021 at 10:54 PM tbpassin ***@***.***> wrote:

> I just checked if leointeg works if started with no leo window open (as it
> should). Yes, it does.
>
Thanks, Tom.  Leo is fortunate to have your thorough testing.

Edward

**Comment by tbpassin** [comment]
Sorry I wasn't clear enough.  What I was talking about is Leo's behavior when a Leo window is open during a vsc session, and both Leo and vsc have the same outline open.  I didn't know if Leo's behavior was provoked by leointeg, the Bridge, or Leo itself.  

In fact, I had never run leointeg when Leo wasn't open.  I don't know why, but it just didn't occur to me to start leointeg with Leo closed.  You might want to add that to the instructions: a Leo Windows does not necessarily have to be open for leointeg to work.

**Comment by boltex** [comment]
Created #182 for that :) Closing this conversation for now. Indeed thanks to @tbpassin for those great concept & ideas! 

(& I'll clear up the readme's requirements for Leo to be 'installed' without even needing tcl/tk or Qt or any GUI subsystem even installed - even less having Leo already opened! haha!)
