### ISSUE TITLE
Create a Font section of leoInteg settings

### ISSUE THREAD

**Issue by edreamleo** [boltex/leointeg#168]
A continuation (and simplification) of #165.

Fonts are the first thing any new leoInteg user will likely want to change. Imo, leoInteg *must* help the user in this regard. The Font section need only contain the following:

- [ ] A link to the "main" setting that handles fonts in the body pane.
- [ ] (Per 165) A discussion of how to use `View: zoom` to adjust the entire screen, namely:

- `View: Zoom In` (Ctrl+=) or `View: Zoom Out` (Ctrl+-) the entire screen until headlines look good.
- Adjust the size of the body font so it looks good at the present zoom level.
- vs-code remembers the zoom setting on reload! 

Imo, this issue is *crucial* for a successful release. We surely don't want to answer the same question dozens or hundreds of times.

**Comment by boltex** [comment]
What is the name of the body font variable in the vscode setting ? Can you paste the section of your settings in vscode that relates to this? ( as an example) as you seem to have found a way to unlink the size ratio between text in the sidebar and the text editors. (Which Is technically what you were trying to achieve in vscode parlance)

**Comment by boltex** [comment]
I'm talking about the Jason version of the settings in case you're seeing the settings as a gui. Top right button to toggle

**Comment by edreamleo** [comment]
On Tue, Jul 20, 2021 at 5:51 PM Felix ***@***.***> wrote:

> What is the name of the body font variable in the vscode setting ?
>
In the gui view, it is [User Tab] Text Editor, Font, Font Size = 14

Let's see if I can find it in the json view:

In Preferences: Open Settings: JSON:

{
    "workbench.colorTheme": "GitHub Dark High Contrast",
    "workbench.startupEditor": "none",
    "leoIntegration.leoEditorPath": "c:\\leo.repo\\leo-editor",
    "leoIntegration.invertNodeContrast": true,
    "window.zoomLevel": 2,
    "leoIntegration.leoPythonCommand": "c:\\scripts\\python.bat",
    "leoIntegration.startServerAutomatically": true,
    "leoIntegration.connectToServerAutomatically": true
}

Note the zoom level above. This gets the headline font to be bigger.

In Preferences: Open Default settings there is a huge list.

The font-related items are:

    // Controls the font family.
    "editor.fontFamily": "Consolas, 'Courier New', monospace",


// Configures font ligatures or font features. Can be either a boolean
to enable/disable ligatures or a string for the value of the CSS
'font-feature-settings' property.
    "editor.fontLigatures": false,

    // Controls the font size in pixels.
    "editor.fontSize": 14,


// Controls the font weight. Accepts "normal" and "bold" keywords or
numbers between 1 and 1000.
    "editor.fontWeight": "normal",

HTH.

Edward

**Comment by boltex** [comment]
So to control the ratio (and get any arbitrary **separate** sizes of fonts in either the sidebar or the editors) the two relevant ones are : 

      **"editor.fontSize"** Controls the font size in pixels of the editor(s) - NOT sidebar. - _but gets multiplied by the zoom level i guess_
      **"window.zoomLevel"** Controls the Overall zoom level, affecting BOTH editor(s) AND sidebar

My plan : Make a 'GUI settings' section in the leointeg settings webview, for now it will contain 2 numeric controls for the fontsize+zoomlevel, that will be linked directly in the users config (like all other other settings in there that are saved and applied  in realtime), and will also show the ratio, and explain more nicely what I just wrote ;)

 (or maybe even at some point in the future, compute real font sizes internally and let the user instead input 2 font sizes in pixels instead of an integer zoom level, and a float fontsize for the editor that is factored by the zoom level)

Anyways this is a great suggestion so thanks for this!! :+1:

**Comment by edreamleo** [comment]
@boltex You're welcome. I should have emphasized in the initial report that the user should set the zoom level *first*, and only after that set the font size.

**Comment by boltex** [comment]
@edreamleo A subject of reflexion: Many extensions's community of users ask their extension developer about changing the font size ratio of their content located in the sidebar in relation with the main editor text size.

If all those people would open an issue in the vscodes github repository, instead of their respective extensions github repository, it would have concatenated all those hundreds of people's upvote already! (and would be implemented) haha!

I think i'm going to maintain a list of those particular points and plan some more thought-out concerted action about it for a later time. When I've gathered enough. (maybe I'll start a union of vscode extension developpers! lol ! )

**Comment by boltex** [comment]
I just found this : https://github.com/microsoft/vscode/issues/519 

Wow! - seems like people did upvote it already in masses! (it's 'on deck' to be implemented relatively soon)
