### ISSUE TITLE
About the "Python Command" setting

### ISSUE THREAD

**Issue by edreamleo** [boltex/leointeg#170]
I was sure I had reported this bug, but maybe only in an email. 

**My original report was wrong**, wherever it was. Sheesh, I think I forgot to pull master! My apologies for any confusion.

**Present situation**

The "Python Command" settings *usually* works. And it works *without* python being on Windows's path.

For example, the following (equivalent) values both work: Note the space in my user name:

`c:\Users\Edward Ream\Python\Python39\python.exe`
`c:\Users\Edward~1\Python\Python39\python.exe`

But the name of a .bat file does *not* work. I have a .bat file (on the Windows path) called python.bat.  This does *not* work as the "Python command" settings:

`python`

This is surprising because typing "python" in a windows console executes python.bat, and therefor ~/Python/Python39/python.exe.

Furthermore, the following also does *not* work:

`python.bat`

However, the *full* path to the same .bat file *does* work:

`c:\scripts\python.bat`

**Summary**:

I like my setup because I can easily switch between a python3.6 and a python3.9 installation. My setup is a strong test of leoInteg's ability to execute python scripts without *any* version of python being on Windows's path.

Earlier experiments showed me that leoserver.py must add leo_editor to sys.path if it not already there. (leoserver.py now does so.) Does this mean that there is no need for the "Leo-Editor path" setting??

I've gone in great detail here because it would be best if *every possible natural way* of starting python actually works in the "Python Command" setting. That way we eliminate as much early confusion as possible.

**Comment by tbpassin** [comment]
That's odd, though, because I'm also starting python from a cmd file on the system path, and it works as expected.  One difference, which you would think wouldn't matter, is that I use the _.cmd_ extension, not _.bat_.  It works even though I don't include the full path, but only the file name.

This is on Windows.  Here are two more things I just noticed:

1. If I don't include the _.cmd_ extension, then the server doesn't get started.
2. The command line that vsc uses includes a mix of "/" and "\" path separators.  Here's the path used when I didn't include the _.cmd_ extension (this is the only way I get enough tome to see and copy it):

`Starting server with command: py-leo-git C:\Tom\git\leo-editor/leo/core/leoserver.py -p 32126`

I'd suggest getting the path separator character to be the right one even if things seem to work this way.

**Comment by boltex** [comment]
I just discovered the concept of 'tasks' in vscode. And that 'tasks' can be used to launch side programs, and that it's easy to specify launching them : https://code.visualstudio.com/api/references/vscode-api#ShellExecution

I'm hopeful I'll get more successes by using this instead of the standard nodejs native child process method that I've been using to start the needed leoserver.py via a specific python launch specification.

:)

**Comment by edreamleo** [comment]
@tbpassin I didn't know about .cmd files!  [This discussion](https://stackoverflow.com/questions/148968/windows-batch-files-bat-vs-cmd) is interesting.

**Comment by tbpassin** [comment]
Yes, _.bat_  is so old-fashioned!  _.cmd_ is the extension to use, but Microsoft doesn't want all those older batch files to stop working so they allow it anyway.  But use _.cmd_ from now on.  _.bat_ is what, perhaps over 9 years out of date.

Apparently Windows does process _.bat_ a little differently from _.cmd._ Here is a discussion: [.bat vs .cmd](https://stackoverflow.com/questions/148968/windows-batch-files-bat-vs-cmd).

**Comment by boltex** [comment]
I'm going to offer more 'process-spawning' options in the configuration panel to help with such issues (starting with the 'shell' option could help with .bat files).

Other options include setting the 'Environment' of the launched process to the project folder path, along with all the new server options I added in the recent days (detach, persist and limit # of users)

Going to do this and cleanup for a day or so before releasing 1.0 :)

**Comment by edreamleo** [comment]
@boltex Thanks for this work. I'll wait for your go-ahead before releasing the next version of Leo. I'm working on distribution issues, so the next release will likely be Leo 6.4 b2.

**Comment by boltex** [comment]
@edreamleo I started https://github.com/boltex/test-spawn to explicitely experiment and test for those things. I'll use it a bit more tomorrow before the new leointeg beta (to set the default settings and help a bit more with launching the server if possible)

**Comment by boltex** [comment]
I noticed different node versions and behavior between vscode extension and plain nodejs. So I've created https://github.com/boltex/test-spawn2 which runs tests from a vscode extension.

**Comment by boltex** [comment]
@edreamleo  New options to control the 'shell' flag when spawning a server is now in the new beta.

 I'll close this issue if it makes your setup with .bat files work (or if other flags/checkboxes in the experimental section of the settings make it work somehow)

**Comment by edreamleo** [comment]
On Sun, Aug 15, 2021 at 10:09 PM Felix ***@***.***> wrote:

> @edreamleo <https://github.com/edreamleo> New options to control the
> 'shell' flag when spawning a server is now in the new beta.
>
> I'll close this issue if it makes your setup with .bat files work (or if
> other flags/checkboxes in the experimental section of the settings make it
> work somehow)
>
Startup appears to work flawlessly, and very quickly!

Edward
