### ISSUE TITLE
Create an API for handling Leonine scripts

### ISSUE THREAD

**Issue by edreamleo** [boltex/leointeg#177]
**Terminology**

- **Leonine scripts** include plugins, `@button`, and `@command` scripts.
- **User-defined commands** are commands defined in Leonine scripts.

#173 exposes glaring problems with server._bad_commands. In general, the LeoServer class can not know which user-defined commands can be run from vs-code! Some user-defined scripts should not be run from vs-code!

**g.in_vs_code**

At minimum, vs-code (that is, leoserver.py) should set g.in_vs_code = True. This would allow plugins to return False in their top-level init functions as necessary.  `@button` or `@command` scripts could test g.in_vs_code and do nothing (with a warning) if the script can't run in vs-code. Ditto for commands defined in plugins.

**Other API extensions**

We probably want some way for user-defined commands to signal that they should *not* be run from vs-code. Not strictly necessary, but it would be useful because leoInteg could silently ignore those user-defined commands. In particular, leoInteg would not show inappropriate `@button` nodes in the "buttons" pane, and the minibuffer would silently ignore inappropriate user-defined commands.

**Comment by tbpassin** [comment]
Basically, any Qt (or GUI) script or plugin can't run under vsc, I suppose.  Are there any others that can't or shouldn't be run in leointeg?  Are there any others which shouldn't run with nullgui?

Ideally, Qt imports via LeoQT would tell leointeg they they aren't to be executable, so all those many plugins wouldn't need to be brought up to date with the new API and restrictions.  Maybe importing from LeoQt could also set a flag that leointeg could check?  That way plugin authors wouldn't need to do anything.  The flag could be set on Commanders, perhaps.  I don't know if there are still any working GUI plugins that don't import from LeoQt or some more generalized API.

**Comment by edreamleo** [comment]
On Thu, Jul 22, 2021 at 2:01 PM tbpassin ***@***.***> wrote:

Hehe, Félix reminds me that we should talk about the client rather than
vs-code. But that's only officially, say in comments in code.  Here I'd
rather talk about vs-code. It's more concrete.

> Basically, any Qt (or GUI) script or plugin can't run under vsc, I
> suppose. Are there any others that can't or shouldn't be run in leointeg?
> Are there any others which shouldn't run with nullgui?
>
I don't think this is the proper question. Imo, we want to limit what
vs-code knows about Leo, and leoserver.py too, for that matter.

I specifically don't want either vs-code or leoserver.py to do any clever
deductions. I want everything to be explicit. Clear?

Edward

**Comment by tbpassin** [comment]
Yes, it's clear, and I agree that it is better engineering design if they don't.  Where, then, do you see the filter or gatekeeper that makes only non-gui commands  available to vs-code, and prevents loading of gui plugins when there is a nullconsole or a text console?  And can we make that work such that all existing commands and plugins don't need to be revised?

**Comment by edreamleo** [comment]
On Thu, Jul 22, 2021 at 5:07 PM tbpassin ***@***.***> wrote:

> Yes, it's clear, and I agree that it is better engineering design if they
> don't. Where, then, do you see the filter or gatekeeper that makes only
> non-gui commands available to vs-code, and prevents loading of gui plugins
> when there is a nullconsole or a text console? And can we make that work
> such that all existing commands and plugins don't need to be revised?
>
I think commands that won't make sense in a client *will* have to be
revised.

In the interim, leoserver.py creates a "bad" list. Entries in the bad list
will correspond to a "switch" in the api. Imo, there is no good substitute
for having Leonine scripts *explicitly* declare that they are (or aren't)
available for execution in clients.

Or so I think now.

Edward

**Comment by tbpassin** [comment]
The only thing is, it would require every writer of commands and plugins to understand what is or is not suitable for clients.  Let's see, you like to include this line:

```
# Fail fast, right after all imports.
g.assertUi('qt')  # May raise g.UiTypeException, caught by the plugins manager.
```

This seems to prevent a plugin from loading when qt has not loaded right, and nothing crashes, right?  I suppose it would be suitable for a command, too, or something like it.

Right now I have an interesting hack to get around a similar problem.  I have a non-gui command that needs to use the clipboard.  Python somehow doesn't have clipboard capability built in, but there are packages available, like pyperclip.  I wanted to avoid using a non-Leo package if I could avoid it.  And you can do this:

```       
from leo.core.leoQt import QtWidgets
QApp = QtWidgets.QApplication
cb = QApp.clipboard()
```

Except that this doesn't work under leointeg.  That's because we don't have a QApplication instance.  You can make it work by using QApplication() instead, so there is an instance to get the clipboard from, but that makes Leo crash when you run the command in an ordinary Leo session (since Leo already has the only allowed instance).

Here's the hack I'm using, and it works as desired -

```
import pyperclip
class Clip:
    def __init__(self):
        from leo.core.leoQt import QtWidgets
        QApp = QtWidgets.QApplication
        cb = QApp.clipboard()

        if cb:
            self.cliptype = 'qt'
            self.cb = cb
        elif pyperclip:
            self.cliptype = 'pyperclip'
        else:
            self.cliptype = None

    def copy(self, text):
        if self.cliptype == 'qt':
            self.cb.setText(text)
        elif self.cliptype == 'pyperclip':
            pyperclip.copy(text)
        else:
            g.es('No clipboard available', color='red')

    def text(self):
        if self.cliptype == 'qt':
            return self.cb.text()
        elif self.cliptype == 'pyperclip':
            return pyperclip.paste()
        else:
            g.es('No clipboard available', color='red')
            return ''

c.clip = Clip()
```

I wanted to import pyperclip conditionally inside the class, but that's not working as yet. I should put its import in a try block, but I already have pyperclip installed so I can wait on that.

So here a case where a non-gui command needs gui help.

Oh, yes, and notice that if c had slots, this approach wouldn't work, since I wouldn't be able to add the non-slot attribute c.clip.

**Comment by edreamleo** [comment]
I am going to close this issue. There is no need for such an API.

@tbpassin I'm convinced, and so is Félix. We both agree that in general nothing bad will happen if the user executes any Leonine script. So, whew!, there is no need for a fancy new API.

There *are* a few commands that should not be executed in Leo's bridge. These are the so-called "bad" commands. Last night Félix and I agreed that in principle either the client or server could maintain separate lists of bad commands. Again, nothing needs to be done now.
