### ISSUE TITLE
Send LeoBridgeServer output to Leo Log Window

### ISSUE THREAD

**Issue by edreamleo** [boltex/leointeg#181]
vs-code has way too many logs. I would like to see all output sent to the LeoBrigeServer log be sent to the Leo Log Window, either in addition to being sent to the LeoBridgeServer log, or instead of being sent.

Not an urgent issue, but imo it would be a good enhancement.

**Comment by boltex** [comment]
Idea / suggestion: Could we not hit two birds with one stone by making this change (as an option or new feature... not sure) in Leo instead?

(maybe its not possible) but how it could work is that, if this option is enabled, the 'print' function could be pointed to the 'g.es' method, so that all print(...) calls end up being g.es(...) calls. Which would show output of print calls to the Leo Log pane. 

(Which would affect both Leo and leointeg, so the user doesn't have to look at two places to see both g.es and print calls output.)
 
any thoughts about that idea? is it a 20 seconds modification or a 20 hours modification? or maybe simply a bad idea ?

**Comment by edreamleo** [comment]
On Sat, Aug 14, 2021 at 12:53 PM Felix ***@***.***> wrote:

> Idea / suggestion: Could we not hit two birds with one stone by making
> this change (as an option or new feature... not sure) in Leo instead?
>

No. Iirc, this feature request is purely a vs-code feature.

Leo already sends log output to the correct place :-) leoserver.py has no
access to a gui log.

Edward

**Comment by boltex** [comment]
@edreamleo good idea indeed. I'll do this small one too for the next release and add an option to turn it on or off for people who like two separate outputs.  👍

**Comment by boltex** [comment]
@edreamleo The more i think of it the more it starts to make sense that the bridge output pane should be eliminated and output be sent to the log pane.
