### ISSUE TITLE
Deprecation warning from leoserver.py

### ISSUE THREAD

**Issue by edreamleo** [boltex/leointeg#194]
When using python 3.9, the following appears in the console from which leoserver.py is launched:
```
server: User Connected, Total: 1, Limit: 1
c:\leo.repo\leo-editor\leo\core\leoserver.py:3383: DeprecationWarning: The explicit passing of coroutine objects to asyncio.wait() is deprecated since Python 3.8, and scheduled for removal in Python 3.11.
  await asyncio.wait([client.send(bytes(json, 'utf-8')) for client in connectionsPool])
```

Imo, this issue can be fixed after releasing leoInteg 1.0.

**Comment by boltex** [comment]
@edreamleo Ah! This is a Leo-editor issue because it's from the server, but you did well in posting it in the leointeg project because i might not have spotted it otherwise perhaps! 

Hmm, I'm not getting those errors in the server so I'm curious as to what exact version of python do you have installed is it 3.9 or is it 3.9.x.y ? 

I'll switch to my windows partition machine and try to update python to the latest available version, and see if I can reproduce and fix the problem. (Those links seem to show it and give solution to it  https://stackoverflow.com/questions/66029772/alternative-to-asyncio-wait https://docs.python.org/3/library/asyncio-task.html#asyncio.wait so I'll do it before you release 6.4 with a bug-free server )

**Comment by boltex** [comment]
I'm in windows now, doing all sorts of operations, writing, moving nodes, detecting external file changes and refreshing... 
Here's a screenshot of a script I ran what shows the version. You can see the version I'm on from there - and also that I don't get the warning/errors out from the terminal output of the server... :/ 
![image](https://user-images.githubusercontent.com/847716/129825125-0643a180-c4c8-422f-9a56-43e1597342ec.png)

I'll try more extreme things to see if I can get the message your getting somehow.,.. maybe you could check to see what kind of operation provokes this warning to appear as output from running the server...

**Comment by boltex** [comment]
Silly me. - Ok i got it while running from an independent console.

probably comes out of err io and not the out io. I've spotted a couple other errors in the server. Fixing'em right now.

**Comment by boltex** [comment]
I fixed it on the felix-server4 branch of leo-editor. It was indeed the server which used deprecated methodolgy as the warning stated.

(I only recently updated the python version to above 3.8 and so i didnt run in independent terminal since... So many thanks for finding this @edreamleo !!!)

Going to make a pull request for this before going to bed :)
