### ISSUE TITLE
Bind Ctrl+Z to Leo:undo and bind Shift+Ctrl+Z to Leo:redo

### ISSUE THREAD

**Issue by edreamleo** [boltex/leointeg#197]
Trying to undo Leo's "extract" command with Ctrl+Z results in the message:

`Unable to create file 'leo:/ekr.20210826075210.1' that already exists when overwrite flag is not set`

**Comment by boltex** [comment]
This issue needs more detailing and/or a detailed resolution plan.

The current modifications to the body pane are currently not sent to Leo until something else happens with the general focus of the window.

 So a 'leo undo' would undo all text changes since text changes are being done in a body pane. That's why - the current and original implementation is to have 'leo undos/redos' be kept apart from the recular undos/redos. available only through the command icons over the outline pane or the palette command.

**Comment by boltex** [comment]
@edreamleo the error vscode is printing has to do with not using the 'leo undo'. using regular undo only works for text changes in the text editor. Once a body pane shows another node, it's matching file in the 'fake' leo-body filesystem is deleted and no longer exists. (until re-selected)

**Comment by edreamleo** [comment]
@boltex It's fine with me to put this off to 1.1 :-)

**Comment by boltex** [comment]
I'll make the 'undo/redo' keybinding(s) perform 'Leo's' undo/redos if focus is on the outline only. Otherwise, normal text editor (body pane edit) undo/redos will be performed. 

I think this makes sense and is somewhat instinctive from a user perspective, although somewhat  slightly deviating from the true Leo behavior.

**Comment by boltex** [comment]
Closing this as it's been fixed (in master since december 2021).

I thought it would have been closed automatically when moved to 'Done in Master' in the project page at https://github.com/boltex/leointeg/projects/1 ... seems the automation is one-way only or i didn't set it up exactly as I wanted hehe ;)
