### ISSUE TITLE
Populate the list of the buttons with @rclick nodes

### ISSUE THREAD

**Issue by ATikhonov2** [boltex/leointeg#241]
I use `@rclick` nodes to organize my multiple buttons in Leo menu. Those nodes are children of a corresponding `@button` node that can even have an empty body. When I open the outline with **LeoInteg** I see only those empty organizing `@button` nodes on the list. Is it possible to teach **LeoInteg** to display my `@rclick` buttons in the tree as well?

Buttons in Leo
<img width="470" alt="image" src="https://user-images.githubusercontent.com/20832685/154001684-9d5031b6-ef7a-4e2b-a5ed-eb0f191a48c8.png">

The same buttons in LeoInteg
<img width="232" alt="image" src="https://user-images.githubusercontent.com/20832685/154001987-fea5c896-af7a-456a-aed5-e8b8374b546f.png">

**Comment by boltex** [comment]
oh! I didn't know about this Leo feature so thanks for creating this issue!!

Should be easy :) 

But, should I show the choices on left-click 'multi-choice popup, if any rclick are present? (because vscode context menus can't be defined at run time) Or, should I list rclick nodes as child of the buttons themselves in the buttons panel, (since this is a 'vscode-tree-view'), and let the user unfold them/click on them ...?

I guess I'll do both and add an options setting for switching this preference.

**Comment by ATikhonov2** [comment]
Either option would be great! Honestly, I would be quite happy just having all my `@rclick` nodes merged into the single plain list of buttons.

**Comment by boltex** [comment]
**Programming Notes:** 
to populate the button pane, use leo's outline positions too, instead of index scripting mod plugin. (  to refer back to specific nodes in order to check for rclick childrens.)

on button press, return do command and return 'ok' if no rclicks were found. 

otherwise, if there are rclicks, return list of possible rclicks as string command names, and position tuple. and offer the original button headline at top,  and all direct rclicks in modal list for user to chose.

Repeat this process recursively if the chosen item's position has child rclicks itself. (and not the top original one.) 

In leoserver, maybe execute the command same way as for minibuffer, as the command-string was given for list anyways and was available in leointeg to point to a specific command to run. or get  the script from the position as in mod scripting plugin.

**Comment by edreamleo** [comment]
@boltex Is there anything you want to add to the server before Leo 6.6 final goes out the door?

**Comment by boltex** [comment]
@ATikhonov2 @edreamleo  This is now done in dev, going to make a merge request tomorrow for leoserver too to work along with it.

**Comment by boltex** [comment]
@ATikhonov2 Everything is ready for this release, so when @edreamleo releases 6.6b2, this will go out too :)  Thanks again for your great suggestions and support!!

**Comment by edreamleo** [comment]
@boltex The only open issue for Leo 6.6 is [#2234](https://github.com/leo-editor/leo-editor/issues/2234). I'll release Leo 6.6b2 tomorrow, Friday, February 25.

**Comment by ATikhonov2** [comment]
I just received the update of LeoInteg. Thank you so much!
