### ISSUE TITLE
unknown reasons for version mismatch

### ISSUE THREAD

**Issue by jabobian** [boltex/leointeg#258]
When I click the buttons of GOTO Panel, I got the following errors,
Please update: Leo 6.6 required for command: : 'find_quick_changed'
Please update: Leo 6.6 required for command: : 'find_quick_marked'
Please update: Leo 6.6 required for command: : 'find_quick_timeline'
Please update: Leo 6.6 required for command: : 'find_quick_history'

However, I have installed Leo 6.6 beta 2 which can be found from Leo menu.

**Comment by jabobian** [comment]
I found VSCode use conda, while I also installed 6.6 outside of conda. So I will try to select proper env in VSCode.

**Comment by jabobian** [comment]
I found in my settings.json, there are conflicts about the python path used.    
```
"leoIntegration.leoEditorPath": "d:\\Programs\\Python\\Python310\\Lib\\site-packages\\leo",
    "leoIntegration.leoPythonCommand": "python3",
    "python.defaultInterpreterPath": "d:\\Miniconda3\\python.exe",
```

**Comment by jabobian** [comment]
I changed 
"python.defaultInterpreterPath": "d:\\Miniconda3\\python.exe"
to
"python.defaultInterpreterPath": "D:\\Programs\\Python\\Python310\\python.exe",
but the error msg still pop up: Please update: Leo 6.6 required for command: : 'find_xxxx'

**Comment by jabobian** [comment]
When I click the Python icon on VSCode sidebar, the "PYTHON:ENVIRONMENTS" panel shows up, and there are two Global Python environments. The d:\Miniconda3\python.exe (3.9.7) is listed before D:\Programs\Python\Python310\python.exe (3.10.3).  Does this matters?

**Comment by boltex** [comment]
Hi @jabobian ! Thank you for trying out LeoInteg and providing feedback! That's how most of the product made progress! :)

Very much appreciated!

First thing you could try is install the latest released Leo : see https://github.com/leo-editor/leo-editor because **the version you claim to have : "Leo 6.6 beta 2" is a version prior to 6.6,** (it's the 6.6 beta 2, the second beta of 6.6, which was before the actual 6.6 - not to be confused with 6.6.2 beta) 

So you would need at least, 6.6 or 6.6.1 (the latest official release), or even the latest development versions, but not 6.6 beta 2! 

If that didn't work, (I'm sure it will 😊 ) here's more info below to help figure out more details...

The python setup for vscode to run and debug your python projects has little to do with the way LeoInteg launches the server:  As it just starts a process (without relation from the vscode python settings) with the simple node.js line : 

`            this._serverProcess = child.spawn(w_pythonPath, w_args, w_options);`

As you might guess from looking at this simple line, the python path is built from the options you've set in the LeoInteg settings view (check out this screenshot below) 
![Screenshot from 2022-05-07 14-08-23](https://user-images.githubusercontent.com/847716/167266878-c628488e-9a2b-4e8c-97d3-fe40ac6d98ac.png)

Note: you can also start the server script yourself in a terminal / bash prompt to try and start it, it's in the leo/core/ folder. 

Also, if you look in the bottom left part of the screenshot, you'll see the 'Leo Log Pane' which, at startup, prints out it's current version along with other info. (Similar to the output of the original Log Pane in Leo.)

Perhaps you could copy-paste what you got in there, to see what Leo version the server is reporting to be using. That would be a good starting point to figure out why LeoInteg complains that it's not using the proper latest version of Leo required. (6.6)

Don't hesitate to add more details or ask more questions!

🦁 Thanks again for trying out and helping finding bugs like you did! 🦁

Félix

**Comment by jabobian** [comment]
@boltex 
In the Leo Log Window, it shows
```
Leo 6.6-b2
Python 3.10.3, LeoGui: dummy version
Windows 10 AMD64 (build 10.0.18363) SP0
```
Then I will try to pip install leo==6.6.1
And now it works perfect.
I noticed that 6.6.1 was released 10 days ago, so I now understand that pip install default is not updated yet.

Much appreciate your kind help and great works!

**Comment by boltex** [comment]
Great! :) 

I'll set this issue ass 'closed' although this issue might come handy also for other people when I update leointeg in the following couple of weeks, which will then require Leo 6.6.3. 

Might be good that I add the solution you provided in the 'version mismatch' message, something like **Try with: pip install leo==6.6.3**

So thanks again for your input @jabobian !
