### ISSUE TITLE
Allow multiple Body panes from different nodes, other than the selected one.

### ISSUE THREAD

**Issue by jabobian** [boltex/leointeg#259]
As we know, in Leo, we can add/delete body editor panes. This is useful when we want to view multple blocks of codes simutaneously.
But in VSCode-LeoInteg, I found there can only be a single LEO:BODY pane.

Please help!

**Comment by boltex** [comment]
Thanks again for your input and suggestions @jabobian ! 

In the first LeoInteg versions back in 2020, it was possible to have many different bodies opened simultaneously, but it was problematic in vscode. (for vscode API related reasons) 

But since then, the API has evolved enough lately that I could bring back that feature. (notably the opened editor tabs features: https://github.com/microsoft/vscode/issues/15178 )

So I'll put this issue on the TODO list for LeoInteg. 

Thank you for bringing this concept back to mind! Much appreciated!!

**Comment by boltex** [comment]
@jabobian Note that opening **more that one of the same body pane** is already available by right clicking on the node and choosing: "Open to the side"

**Comment by jabobian** [comment]
Thank you, boltex. I know that open to the side can open a pane for the same body, but click any other node will clear that pane. So we are looking forward to see the enhanced version of open to the side. :-)

**Comment by boltex** [comment]
@jabobian I've started tackling this issue in LeoJS first (https://github.com/boltex/leojs/issues/120) I'll implement it in LeoInteg also as soon as it's working.
