### ISSUE TITLE
Implement commands to select, expand and contract outline nodes

### ISSUE THREAD

**Issue by boltex** [boltex/leointeg#30]
Some commands to select, expand and contract outline nodes could be implemented

(such as Alt-Home (goto-first-visible-node), Alt-End (goto-last-visible-node), Alt-arrow keys, ...)
 
See http://leoeditor.com/commands.html#selecting-outline-nodes

**Comment by edreamleo** [comment]
@boltex Perhaps this is the place for a general comment about supporting Leo commands. This comment applies to several other leoInteg issues.

Imo, the only way to support Leo's full complement of commands is to query Leo for the list of expanded and marked nodes, as well as c.p, the presently selected node.

Special cases for individual commands can not really ever be enough, because of Leo commands such as execute-script, which can trigger any importer, or any other code that can insert, delete, change or rearrange nodes. In such cases, it seems to me, leoInteg will be obliged to redraw the entire outline, presumably by asking Leo's bridge to describe the entire outline, including, as I say above, the list of  expanded and marked nodes, as well as c.p, the presently selected node.

**Comment by boltex** [comment]
@edreamleo  Yep,. this was already started with #18 but I've made additions to this in the current work for the next 0.1.13 release.

When refreshing the tree, the nodes know if they're marked, clones , etc. and should propose commands that reflect that state. (right click on marked node to see 'unmark' instead of mark  @files nodes show "refresh from disk" ,, 

And for general states, after each command stack that finishes resolving, i call a debounced method to ask leo about the current selected node and Leo state in general to enable/disable commands and icons.: 
(sample python below)
w_states["changed"] = self.commander.changed   # 'dirty/changed' member
w_states["canUndo"] = self.commander.canUndo()
w_states["canRedo"] = self.commander.canRedo()
w_states["canDemote"] = self.commander.canDemote()
w_states["canDehoist"] = self.commander.canDehoist()

This will be apparent and usable in the next release. (or on the dev branch a bit later tonight)

**Comment by edreamleo** [comment]
@boltex You're welcome. The plan you propose seems good to me.

**Comment by edreamleo** [comment]
@boltex As I have noted elsewhere, executing a recursive import script (in leoInteg) via Ctrl+B works. This indicates that leoInteg is mostly correct and complete.
